### ISSUE TITLE
Setting `rgb_temperature` causes an error

### ISSUE THREAD

**Issue by fr3fou** [xplus2/homeassistant-ambient-extractor#1]
![image](https://user-images.githubusercontent.com/1344906/218980499-ff32bee6-11dd-40fb-aedb-7ae6215198bc.png)

Setting the `rgb_temperature` parameter seems to not be working correctly, looking at the code
https://github.com/xplus2/homeassistant-ambient-extractor/blob/6042fe14ccdc6ade32e0f4bbe3681ede9d83f4c4/custom_components/ambient_extractor/__init__.py#L152-L156
I'm guessing the final value overflows over 255 and causes this error. 
```yaml
service: ambient_extractor.turn_on
data_template:
  brightness_max: 140
  brightness_min: 70
  brightness_auto: true
  brightness_mode: dominant
  transition: 5
  rgb_temperature: 5 # This thing breaks it
  ambient_extract_url: "..."
target:
  entity_id: light.main_lights
  ```
  Only very low values (like `2`) seem to work, but even then it still crashes sometimes
